server:
  port: 8080

spring:
  application:
    name: order

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000  # 연결 timeout
        readTimeout: 610      # 응답 대기 timeout
        retryer:
          period: 2000        # 재시도 주기 
          maxPeriod: 5000     # 최대 재시도 주기 
          maxAttempts: 2      # 최대 재시도 횟수 
hystrix:
  command:
    # 전역설정
    default:
      execution.isolation.thread.timeoutInMilliseconds: 610 # 읽기 타임아웃 (밀리초 단위)
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: labshoppubsub
          contentType: application/json
        event-out:
          destination: labshoppubsub
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

api:
  url:
    inventory: localhost:8082

server:
  port: 8081

---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: labshoppubsub
          contentType: application/json
        event-out:
          destination: labshoppubsub
          contentType: application/json

api:
  url:
    inventory: inventory:8080

